export interface Archetype {
  name: string
  description: string
  table: { firstName: string; lastName: string; race: string; quirk: string }[]
}

export const ARCHETYPES: Archetype[] = [
  {
    name: 'The Merchant',
    description: 'Traders, shopkeeps, and dealers of wares',
    table: [
      { firstName: 'Theron', lastName: 'Blackwood', race: 'Human', quirk: 'Always counting coins' },
      { firstName: 'Mira', lastName: 'Thorngage', race: 'Halfling', quirk: 'Speaks in prices' },
      { firstName: 'Dural', lastName: 'Ironbrand', race: 'Dwarf', quirk: 'Bites coins to test them' },
      { firstName: 'Selene', lastName: 'Moonweaver', race: 'Elf', quirk: 'Never names the price first' },
      { firstName: 'Gorrick', lastName: 'Tallstone', race: 'Goliath', quirk: 'Whispers when discussing money' },
      { firstName: 'Pip', lastName: 'Bramblesnap', race: 'Gnome', quirk: 'Keeps a ledger of favors' },
      { firstName: 'Vashra', lastName: 'Saltwind', race: 'Tiefling', quirk: 'Only trades in odd numbers' },
      { firstName: 'Berrick', lastName: 'Goldmantle', race: 'Human', quirk: 'Wears all their wealth' },
      { firstName: 'Nessa', lastName: 'Copperkettle', race: 'Halfling', quirk: 'Offers tea with every deal' },
      { firstName: 'Thrak', lastName: 'Bonegrinder', race: 'Half-Orc', quirk: 'Surprisingly gentle haggler' },
      { firstName: 'Elara', lastName: 'Silkthread', race: 'Elf', quirk: 'Remembers every sale perfectly' },
      { firstName: 'Dorin', lastName: 'Hammerfell', race: 'Dwarf', quirk: 'Tests everything by smell' },
      { firstName: 'Zara', lastName: 'Brightscale', race: 'Dragonborn', quirk: 'Collects stories as payment' },
      { firstName: 'Wendell', lastName: 'Fairprice', race: 'Human', quirk: 'Name is deeply ironic' },
      { firstName: 'Tilla', lastName: 'Wanderfoot', race: 'Halfling', quirk: 'Sells things found on the road' },
      { firstName: 'Grimjaw', lastName: 'Steelworth', race: 'Dwarf', quirk: 'Won\'t sell to rude customers' },
      { firstName: 'Lyris', lastName: 'Starmarket', race: 'Elf', quirk: 'Only opens shop at twilight' },
      { firstName: 'Bort', lastName: 'Mudbucket', race: 'Goblin', quirk: 'Shockingly honest' },
      { firstName: 'Cassandra', lastName: 'Velvetpurse', race: 'Human', quirk: 'Has a contact everywhere' },
      { firstName: 'Flint', lastName: 'Ashwood', race: 'Half-Elf', quirk: 'Carves prices into the counter' },
    ],
  },
  {
    name: 'The Scholar',
    description: 'Sages, wizards, and seekers of knowledge',
    table: [
      { firstName: 'Aldric', lastName: 'Quillsworth', race: 'Human', quirk: 'Ink-stained fingers always' },
      { firstName: 'Fennara', lastName: 'Bookbinder', race: 'Gnome', quirk: 'Talks to books' },
      { firstName: 'Orin', lastName: 'Dustmantle', race: 'Dwarf', quirk: 'Allergic to their own library' },
      { firstName: 'Seraphina', lastName: 'Lorekeep', race: 'Elf', quirk: 'Corrects everyone, always' },
      { firstName: 'Hadrian', lastName: 'Greystone', race: 'Human', quirk: 'Forgets names, remembers dates' },
      { firstName: 'Wicket', lastName: 'Sparkscribe', race: 'Gnome', quirk: 'Writes notes on their arms' },
      { firstName: 'Morgath', lastName: 'Tombread', race: 'Tiefling', quirk: 'Only studies forbidden topics' },
      { firstName: 'Yennefer', lastName: 'Ashenveil', race: 'Half-Elf', quirk: 'Speaks in footnotes' },
      { firstName: 'Braum', lastName: 'Runehammer', race: 'Dwarf', quirk: 'Carves notes into stone tablets' },
      { firstName: 'Isadora', lastName: 'Dawnscript', race: 'Human', quirk: 'Reads while walking' },
      { firstName: 'Thistledown', lastName: 'Pagecurl', race: 'Halfling', quirk: 'Has a book for every occasion' },
      { firstName: 'Vex', lastName: 'Inkblot', race: 'Tiefling', quirk: 'Invents words when stuck' },
      { firstName: 'Calista', lastName: 'Starcharter', race: 'Elf', quirk: 'Only works by moonlight' },
      { firstName: 'Roland', lastName: 'Thickspine', race: 'Human', quirk: 'Uses books as armor' },
      { firstName: 'Mizzle', lastName: 'Copperlens', race: 'Gnome', quirk: 'Has seven pairs of glasses' },
      { firstName: 'Korrath', lastName: 'Boneread', race: 'Dragonborn', quirk: 'Reads omens in everything' },
      { firstName: 'Elwin', lastName: 'Mapfold', race: 'Half-Elf', quirk: 'Terrible sense of direction' },
      { firstName: 'Prudence', lastName: 'Lastpage', race: 'Human', quirk: 'Always reads the ending first' },
      { firstName: 'Snib', lastName: 'Scrollsnatch', race: 'Goblin', quirk: 'Self-taught, very proud' },
      { firstName: 'Thalia', lastName: 'Deepquill', race: 'Elf', quirk: 'Writes everything in verse' },
    ],
  },
  {
    name: 'The Guard',
    description: 'Soldiers, watchkeepers, and enforcers',
    table: [
      { firstName: 'Marcus', lastName: 'Shieldwall', race: 'Human', quirk: 'Never sits with back to door' },
      { firstName: 'Brunhild', lastName: 'Ironjaw', race: 'Dwarf', quirk: 'Counts exits in every room' },
      { firstName: 'Kael', lastName: 'Nightwatch', race: 'Half-Elf', quirk: 'Sleeps with one eye open' },
      { firstName: 'Torga', lastName: 'Skullsplitter', race: 'Half-Orc', quirk: 'Surprisingly philosophical' },
      { firstName: 'Elena', lastName: 'Brightblade', race: 'Human', quirk: 'Polishes sword constantly' },
      { firstName: 'Stenn', lastName: 'Wallbreaker', race: 'Goliath', quirk: 'Speaks only in short sentences' },
      { firstName: 'Roswyn', lastName: 'Quickstep', race: 'Halfling', quirk: 'Overcompensates for height' },
      { firstName: 'Voss', lastName: 'Dreadhelm', race: 'Tiefling', quirk: 'Never removes their helmet' },
      { firstName: 'Gareth', lastName: 'Oathkeeper', race: 'Human', quirk: 'Takes every promise literally' },
      { firstName: 'Dagny', lastName: 'Hammershout', race: 'Dwarf', quirk: 'Yells orders at civilians' },
      { firstName: 'Ashara', lastName: 'Longbow', race: 'Elf', quirk: 'Prefers ranged solutions' },
      { firstName: 'Brick', lastName: 'Stonefist', race: 'Goliath', quirk: 'Gentle with children' },
      { firstName: 'Lira', lastName: 'Shadowstep', race: 'Human', quirk: 'Was definitely a thief before' },
      { firstName: 'Bram', lastName: 'Copperbell', race: 'Halfling', quirk: 'Rings bell at trouble' },
      { firstName: 'Azar', lastName: 'Flameguard', race: 'Dragonborn', quirk: 'Breathes fire when angry' },
      { firstName: 'Henrik', lastName: 'Dullblade', race: 'Human', quirk: 'Weapon is ceremonial only' },
      { firstName: 'Tessara', lastName: 'Moonwatch', race: 'Elf', quirk: 'Only patrols at night' },
      { firstName: 'Grot', lastName: 'Loudmouth', race: 'Half-Orc', quirk: 'Announces everything' },
      { firstName: 'Petra', lastName: 'Gatekeep', race: 'Dwarf', quirk: 'Asks too many questions' },
      { firstName: 'Finn', lastName: 'Deserter', race: 'Human', quirk: 'Doesn\'t talk about the war' },
    ],
  },
  {
    name: 'The Tavern',
    description: 'Innkeepers, barkeeps, and tavern regulars',
    table: [
      { firstName: 'Barnaby', lastName: 'Fullmug', race: 'Human', quirk: 'Never lets a glass go empty' },
      { firstName: 'Greta', lastName: 'Hearthstone', race: 'Dwarf', quirk: 'Knows everyone\'s usual' },
      { firstName: 'Rolo', lastName: 'Tumbleweed', race: 'Halfling', quirk: 'Juggles while serving' },
      { firstName: 'Vera', lastName: 'Blackbarrel', race: 'Human', quirk: 'Brews illegal spirits' },
      { firstName: 'Throgg', lastName: 'Gentle', race: 'Half-Orc', quirk: 'Bouncer who hates violence' },
      { firstName: 'Maeve', lastName: 'Songbird', race: 'Half-Elf', quirk: 'Hums while she works' },
      { firstName: 'Dunkin', lastName: 'Stoutbelly', race: 'Dwarf', quirk: 'Tastes everything twice' },
      { firstName: 'Sylva', lastName: 'Greenvine', race: 'Elf', quirk: 'Only serves elven wine' },
      { firstName: 'Hodge', lastName: 'Barsworth', race: 'Human', quirk: 'Has heard every story' },
      { firstName: 'Tink', lastName: 'Bottlecap', race: 'Gnome', quirk: 'Invents cocktails on the spot' },
      { firstName: 'Zarash', lastName: 'Firebrew', race: 'Tiefling', quirk: 'Drinks are literally warm' },
      { firstName: 'Polly', lastName: 'Lastcall', race: 'Human', quirk: 'Never closes on time' },
      { firstName: 'Bramble', lastName: 'Corkpop', race: 'Halfling', quirk: 'Tells terrible jokes' },
      { firstName: 'Gundar', lastName: 'Alebeard', race: 'Dwarf', quirk: 'Beard smells like hops' },
      { firstName: 'Celeste', lastName: 'Moondrop', race: 'Elf', quirk: 'Reads fortunes in foam' },
      { firstName: 'Big Red', lastName: 'Unknown', race: 'Dragonborn', quirk: 'No one knows their real name' },
      { firstName: 'Willa', lastName: 'Warmhearth', race: 'Human', quirk: 'Adopts every stray' },
      { firstName: 'Snag', lastName: 'Brokenbottle', race: 'Goblin', quirk: 'Glass is always half empty' },
      { firstName: 'Otto', lastName: 'Nightowl', race: 'Human', quirk: 'Only works the graveyard shift' },
      { firstName: 'Fern', lastName: 'Meadowbrew', race: 'Half-Elf', quirk: 'Every drink has a flower in it' },
    ],
  },
]
